---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-spot-price-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-spot-price-monitor
subjects:
- kind: ServiceAccount
  name: k8s-spot-price-monitor
  namespace: kube-system
